CREATE TABLE ROLES (
	ROLE_ID VARCHAR (5) NOT NULL, 
	ROLE_DES VARCHAR (30) NOT NULL,
	PRIMARY KEY (ROLE)
); 

CREATE TABLE LOGIN (
	USER_NAME VARCHAR (10) NOT NULL,
	PASSWORD VARCHAR (32),
	ROLE_ID VARCHAR (5), 
	PRIMARY KEY (USER_ID, USER_NAME)
	FOREIGN KEY (ROLE) REFERENCES ROLES(ROLE_ID)
);

CREATE TABLE INVESTOR_SIGNUP (
	INVESTOR_USER_ID VARCHAR (10) NOT NULL, 
	FIRST_NAME VARCHAR (32) NOT NULL,
	LAST_NAME VARCHAR (32) NOT NULL,
	MIDDLE_NAME VARCHAR (32),
	COUNTRY_CODE INT (4),
	PHONE_NUMBER INT (10),
	DATE_OF_BIRTH DATE
	START_DATE DATE
	EXPIRY_DATE DATE
	PRIMARY KEY (USER_ID)
);

CREATE TABLE COMPANY (
	COMPANY_CODE VARCHAR (5),
	COMPANY_TITLE VARCHAR (20),
	COMPANY_ADDRESS VARCHAR(64),
	COMPANY_SECTOR VARCHAR(20),
	PRIMARY KEY(COMPANY_CODE)
); 

CREATE  TABLE COMPANY_SHARE TRADE (
	COMPANY_CODE VARCHAR (5),
	COMPANY_INVESTOR_ID VARCHAR (10)
	COMPANY_TURNOVER FLOAT,
	COMPANY_OPENSHARE_PRICE FLOAT,
	PRIMARY KEY(COMPANY_CODE)
);
  
CREATE TABLE STOCK_PRICES (
	STOCK_COMPANY_CODE VARCHAR (5),
	STOCK_COMPANY_EXCHANGE VARCHAR (8),
	STOCK_CURRENT_PRICE FLOAT,
	STOCK_DATE DATE,
	STOCK_TIME TIMESTAMP,
	STOCK_COMPANY_IPO FLOAT,
	STOCK_CURRENCY VARCHAR (5),
	STOCK_TURNOVER FLOAT,
	PRIMARY KEY (STOCK_COMPANY_CODE)
);

CREATE TABLE COMMODITY (
	COMMODITY_COMPANY_CODE VARCHAR (5),
	COMMODITY_ID VARCHAR(8),
	COMMODITY_DESC VARCHAR(32),
	COMMODITY_PRICE FLOAT,
	PRIMARY KEY (COMMODITY_ID)
);

CREATE TABLE INVESTOR_OPERATIONS (
	COMPANY_INVESTOR_ID VARCHAR
	COMPANY_CODE VARCHAR
	TRADE_TYPE VARCHAR 2 
	TRADE_CATEGORY VARCHAR 4
	TRADE_DATE DATE
	BUYING_PRICE FLOAT
	SELLING_PRICE FLOAT
	STOCK_BUYING_CURRENCY VARCHAR 5
	STOCK_SELLING_CURRENCY VARCHAR 5
);







